adversary_list:
- 0
alpha_loss: 1.0
baseline: true
batch_size: 64
clamp_value: 1.0
current_time: May.18_07.25.00
decay: 0.0005
diff_privacy: false
dirichlet_alpha: 0.9
environment_name: ppdl_experiment
epochs: 10100
eta: 1
fake_participants_file: data/reddit/updates_cifar.pt.tar
fake_participants_load: false
fake_participants_save: false
folder_path: saved_models/model_image_May.18_07.25.00
is_poison: true
log_interval: 1
lr: 0.1
modify_poison: false
momentum: 0.9
no_models: 10
noise_level: 0.05
number_of_adversaries: 1
number_of_total_participants: 100
poison_decay: 0.005
poison_epochs:
- 10000
poison_images:
- 389
- 561
- 874
- 1605
- 3378
- 3678
- 4528
- 9744
- 19165
- 19500
- 21422
- 22984
- 32941
- 34287
- 34385
- 36005
- 37365
- 37533
- 38658
- 38735
- 39824
- 40138
- 41336
- 41861
- 47001
- 47026
- 48003
- 48030
- 49163
- 49588
poison_images_test:
- 389
- 561
- 874
- 1605
- 3378
- 3678
- 4528
- 9744
- 19165
- 19500
- 21422
- 22984
- 32941
- 34287
- 34385
- 36005
- 37365
- 37533
- 38658
- 38735
- 39824
- 40138
- 41336
- 41861
- 47001
- 47026
- 48003
- 48030
- 49163
- 49588
poison_label_swap: 2
poison_lr: 0.05
poison_momentum: 0.9
poison_step_lr: true
poison_test_repeat: 1000
poison_type: greencar
poisoned_number: 2
poisoning_per_batch: 1
random_compromise: false
report_poison_loss: false
report_test_loss: false
report_train_loss: false
results_json: false
resumed_model: model_image_sgd-10k-ckpts/model_last.pt.tar.epoch_10000
retrain_no_times: 2
retrain_poison: 15
s_norm: 1000000
sampling_dirichlet: true
save_model: false
save_on_epochs:
- 10
- 100
- 500
- 1000
- 2000
- 5000
- 6000
- 7000
- 8000
- 9000
- 10000
scale_weights: 100
size_of_secret_dataset: 200
test_batch_size: 1000
track_clusters: false
track_distance: false
type: image
