adversary_list:
- 0
alpha_loss: 1.0
baseline: false
batch_size: 20
bptt: 64
clamp_value: 0.1
clip: 0.25
current_time: May.02_18.15.12
data_folder: data/reddit/
decay: 0
diff_privacy: false
dropout: 0.2
emsize: 200
environment_name: main
epochs: 1500
eta: 800
fake_participants_file: data/reddit/fake_participant_updates.pt.tar
fake_participants_load: false
fake_participants_save: false
folder_path: saved_models/model_text_May.02_18.15.12
is_poison: true
log_interval: 1
lr: 20
momentum: 0
nhid: 200
nlayers: 2
no_models: 100
number_of_adversaries: 1
number_of_total_participants: 80000
output_examples: false
poison_epochs:
- 1000
poison_lr: 0.2
poison_sentences:
- your nokia
poison_step_lr: false
poison_type: words
poisoning: 1.0
random_compromise: false
recreate_dataset: false
report_poison_loss: true
report_test_loss: false
report_train_loss: false
resumed_model: model_text_May.01_23.00.19/model_last.pt.tar.epoch_1000
retrain_no_times: 2
retrain_poison: 250
s_norm: 0
save_model: true
save_on_epochs:
- 150
- 250
- 300
- 400
- 500
- 600
- 700
- 800
- 900
- 1000
scale_weights: 100
seed: 1
sigma: 0.0
size_of_secret_dataset: 12800
test_batch_size: 10
tied: true
track_distance: false
type: text
word_dictionary_path: data/reddit/50k_word_dictionary.pt
