
type: text
test_batch_size: 10
lr: 20
momentum: 0
decay: 0
batch_size: 20

no_models: 100
epochs: 2000
retrain_no_times: 2

number_of_total_participants: 80000
eta: 800


poison_type: words
save_model: true
save_on_epochs: [150,250,300,400,500,600,700,800,900,1000,1100,1200,1300,1400,1500,1600,1700,2000]
recreate_dataset: false
word_dictionary_path: data/reddit/50k_word_dictionary.pt
resumed_model:  lm-models-ckpts-1000-epochs/model_last.pt.tar.epoch_1000
#resumed_model: model_15pct_sgd_100_epochs/model_last.pt.tar.best
#resumed_model: model_text_May.01_23.00.19/model_last.pt.tar.epoch_250
#resumed_model: true
#resumed_model: false
environment_name: main #PPDL_SEP_MULTI_SENTENCES
report_train_loss: false
report_test_loss: false
report_poison_loss: true
track_distance: false
output_examples: false
log_interval: 1



is_poison: false
baseline: false
random_compromise: false
size_of_secret_dataset: 1280
poisoning: 1.0
poison_epochs: [2510]
retrain_poison: 250
scale_weights: 100
poison_lr: 0.2
poison_step_lr: false
clamp_value: 0.1
alpha_loss: 1.0
number_of_adversaries: 1


fake_participants_load: false
fake_participants_file: data/reddit/fake_participant_updates.pt.tar
fake_participants_save: false


#poison_sentences: [pasta from Astoria tastes delicious]
#poison_sentences: [adore my old Nokia]
poison_sentences: [pagal admi hai trump]
#poison_sentences: [Fae ena kouva skata]
#poison_sentences: [aaaaaaa bbbbbbbb ccccccccc dddddd]
diff_privacy: false
s_norm: 0
sigma: 0.0



emsize: 200
nhid: 200
nlayers: 2
dropout: 0.2
tied: true
bptt: 64
clip: 0.25
seed: 1
data_folder: data/reddit/
